### ISSUE TITLE
Disable login dialog for files with public read permission?

### ISSUE THREAD

**Issue by samuell** [DICE-UNC/irods-webdav#14]
We are looking into the possibility of using irods-webdav for publishing stable URL:s to published datasets. 

One of the things we need is to provide files that are accessible by anyone, without login. But from my tests, I haven't been able to disable the login dialog when accessing files that have public read (nor even public own) permissions in the ACL.

Is this possible to configure somehow?

**Comment by michael-conway** [comment]
I think it would be possible by hard-coding an anonymous user id.

Would REST or the new web interface work be a better venue for this?
WebDav is not very user friendly.  We have been developing the concept of a
'home page' for a data object or collection that is resolvable as an HTTP
URI for this purpose, and I think that's a better route.  We want to employ
those URIs for Linked Data in DFC.

**Comment by samuell** [comment]
@michael-conway Ah, IC. Thanks for the quick response!

Is [1] what you mean with "the web interface"? ... or a new version of the iDrop?

Also, could you mention very shortly the status about those two, the UI and the REST interface? We are looking for something that is ready to put into production, but doesn't have some of the limitations and complexity, of the old iDrop interface.

The 'home page' concept sounds very very interesting btw!

[1] https://github.com/DICE-UNC/irods-cloud-browser

**Comment by michael-conway** [comment]
We mean the irods-cloud-browser app.  I expect we will have an initial
release in about a month, it will be much cleaner than the prior web
interface.  It also supports deep linking, which makes it a good candidate
for your scenario.

My hope is to EOL the old iDrop codebase as soon as possible, it has gotten
quite long in the tooth.

**Comment by samuell** [comment]
IC, many thanks for the info!

**Comment by michael-conway** [comment]
will look into an enhancement to support html pages from Milton, now that we have enterprise keys.  Will close this one for now.
