### ISSUE TITLE
Users authenticating through PAM 

### ISSUE THREAD

**Issue by jrtmendoza** [DICE-UNC/irods-webdav#15]
Hello, 

May I ask how I can enable users authenticating through pam to login to irods-webdav? Internal users such as rods can login just fine. I've already modified the authscheme in the milton build file to PAM. Are there any more changes that I need to make?

**Comment by michael-conway** [comment]
that should be sufficient, Note that your SSL certs either have to be standard ones pre-included in Java, or imported into the cacerts for your platform via keytool.

PAM is actually just indicated in the IRODSAccount in Jargon, and setting the additional info in the milton xml config gives the host/port/resource/zone/auth scheme to add to the basic auth credentials coming in.

Let me know if you run into any issues.
