### ISSUE TITLE
touch: cannot touch ‘blah’: Input/output error

### ISSUE THREAD

**Issue by jerry57** [DICE-UNC/irods-webdav#20]
mounting WebDav via linux mount.davfs and trying to create a file using touch results in the above error.

I can read listing of files using ls of mounted directory
I can read contents of files using cat <filename> of files in mounted store
I can delete files in the mounted directory

creating or editing the file results in the error though.  Ironically it does create a zero byte file though.

I am on Ubuntu 14.04 fully updated system as of 2015-08-19

**Comment by michael-conway** [comment]
getting ready to implement new milton and release an 'enterprise' version, we can retest on that push

**Comment by michael-conway** [comment]
fixed in upcoming rc1
