### ISSUE TITLE
attempting to mount webdav filesystem results in long pause, no message, failed attempt

### ISSUE THREAD

**Issue by jerry57** [DICE-UNC/irods-webdav#31]
I attempted to mount a remote webdav filesystem but it appears to fail without an error message of any sort.  This was on a Mac OS X 10.10 system.

poplar:~ jerry$ mount_webdav -i http://vm64-243.iplantcollaborative.org/ipctest /Users/jerry/webdav_mount/
Username: ipctest
Password: 

poplar:~ jerry$ 
poplar:~ jerry$ 
poplar:~ jerry$ 
poplar:~ jerry$ 
poplar:~ jerry$ df -h
Filesystem      Size   Used  Avail Capacity   iused    ifree %iused  Mounted on
/dev/disk1     465Gi  420Gi   44Gi    91% 110234204 11603394   90%   /
devfs          185Ki  185Ki    0Bi   100%       640        0  100%   /dev
map -hosts       0Bi    0Bi    0Bi   100%         0        0  100%   /net
map auto_home    0Bi    0Bi    0Bi   100%         0        0  100%   /home
poplar:~ jerry$ mount
/dev/disk1 on / (hfs, local, journaled)
devfs on /dev (devfs, local, nobrowse)
map -hosts on /net (autofs, nosuid, automounted, nobrowse)
map auto_home on /home (autofs, automounted, nobrowse)

**Comment by michael-conway** [comment]
This issue does not seem to arise in testing, will close for now
