### ISSUE TITLE
bonnie errors at cyverse

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/irods-webdav#34]
running my shellscript that creates/copies/moves/deletes files of various sizes checking their chksums appears to be working.  However, running Bonnie or Bonnie++ against the filesystem is failing either immediately (bonnie++) with "Using uid:1000, gid:1000." and error of "Can't open file ./Bonnie.####" or fails after "Writing a byte at a time...done" with error "Can't open file ./Bonnie.####"

**Comment by michael-conway** [comment]
Bonnie commandlines were:

```
bonnie -d /webdavfs/webdav_mount/WebDav_Testing -s 48G -m WebDav

```
or

```
bonnie++ -d /webdavfs/webdav_mount -s 48G -n 0 -m TEST -f -b -u xxx
```

**Comment by michael-conway** [comment]
ran locally, seemed to run, but I'm out of disk space ;-O



[root@ils00213 bonnie++-1.03e]# ./bonnie++ -d /home/mconway/webdav_mount/bonnie -u root
Using uid:0, gid:0.
Writing with putc()...Can't putc() - disk full?
[root@ils00213 bonnie++-1.03e]#

**Comment by jerry57** [comment]
I retried today as root and normal user (myself), still can't get it to run.  Keep getting Can't open file error.
I have tried mount points that were within the user's home directory and those off of the machine root  Ownership on the folder and mount point are for the user accessing it (i.e.: jerry:jerry)  Permissions on the mounted folder were 755

Running as root made no difference.  Specifying the user (-u jerry:jerry or -u root) made no difference
I also tried very minimal commandline of:
bonnie++ -d /webdavfs/webdav_mount -m EvilTester
it seems to start:
writing a byte at a time...
for a bit and then I get:
Can't open file ./Bonnie.#####

The bonnie++ I am running is version:
Version: 1.97
on Ubuntu 14.04

**Comment by michael-conway** [comment]
I'll try it on my laptop. I just ran out of room on this desktop machine running it

**Comment by michael-conway** [comment]
yeah I need to figure out what it wants, it does run if i run bonnie++ as sudo with -u root, but only then.  I suspect it's not on the back end side, rather in webdav on the client, but at least let me see if I can get bonnie++ to run when there is sufficient space here

**Comment by michael-conway** [comment]
I think I see it on this box with more space.  It looks to me the issue may be davfs itself?  For my situation I started bonnie++, 

```

Using uid:0, gid:0.
Writing with putc()...done
Can't open file ./Bonnie.9297.000

```

Which sounds a lot like the indicated issue.  I see a ton of 1.1 gb files out there on iRODS, but that
particular file is not there.  My computer (ubuntu laptop) is now pretty sluggish, however, the iRODS and webdav docker images are still up, show no errors, and are responsive from both ils and from accessing webdav via the web browser and http.  The local mount seems a bit cheezed.

**Comment by michael-conway** [comment]
Tested on my laptop with a 1tb drive.  I find that it just kills this computer and rapidly fills up the drive, so I'm not quite sure this is the right tool to test?  I started looking at Tsung or JMeter as a way to do functional testing and am considering adding a suite of that type, I'm concerned here we're testing the davfs implementation here, not the backend.  I'm trying to pick that apart.

**Comment by michael-conway** [comment]
Plan here is to sidestep bonnie++ for now and build in a JMeter based load/functional test suite, I want to see whether this more transparent method can reveal where issue lies (is it davfs, docker, etc).  I'll cut a release here and then restructure the project to have a test suite submodule.

**Comment by jerry57** [comment]
We have the ability to use JMeter here.  What are the parts you want to test/load out?  Do you have a set of steps you want to walk through?  Are you planning on using icommands and OS Process sampler or jargon somehow?  Are you planning on focusing on Mac OS or Linux first?  iRODS 4 or 3.3 clients?

**Comment by michael-conway** [comment]
Hey Jerry, I'm going to create a set of custom samplers and put them under
the webdav project repo.  The sketch I have is

- a test setup class that will prepare a set of dirs based on a properties
file
- mount via davfs
- run load and functional tests against davfs
- run direct HTTP tests against the apache

We can use both routes to exercise by http and by treating the mounted dir
as java.io files and streams, in this manner we can run file system level
tests on unix, windows, and mac

So when that's in it should be something you could just run in your CI
directly.
